<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Arbor.Processing" Version="*" />
    <PackageReference Include="JetBrains.Annotations" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="*" />
    <PackageReference Include="Serilog" Version="*" />
    <PackageReference Include="Serilog.Sinks.Console" Version="*" />
    <PackageReference Include="Serilog.Sinks.File" Version="*" />
    <PackageReference Include="System.Collections.Immutable" Version="*" />
    <PackageReference Include="Arbor.KVConfiguration.UserConfiguration" Version="*" />
    <PackageReference Include="Arbor.KVConfiguration.JsonConfiguration" Version="*" />
    <PackageReference Include="Newtonsoft.Json" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Milou.Deployer.Core\Milou.Deployer.Core.csproj" />
    <ProjectReference Include="..\Milou.Deployer.Ftp\Milou.Deployer.Ftp.csproj" />
    <ProjectReference Include="..\Milou.Deployer.IIS\Milou.Deployer.IIS.csproj" />
    <ProjectReference Include="..\Milou.Deployer.Waws\Milou.Deployer.Waws.csproj" />
  </ItemGroup>

</Project>
