<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Arbor.App.Extensions" Version="*-*" />
    <PackageReference Include="Arbor.KVConfiguration.Core" Version="*-*" />
    <PackageReference Include="Arbor.KVConfiguration.Schema.Json" Version="*-*" />
    <PackageReference Include="Arbor.KVConfiguration.Urns" Version="*-*" />
    <PackageReference Include="Arbor.Processing" Version="*" />
    <PackageReference Include="Arbor.Tooler" Version="*-*" />
    <PackageReference Include="MediatR" Version="*" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="*" />
    <PackageReference Include="Microsoft.Web.Xdt" Version="*" />
    <PackageReference Include="JetBrains.Annotations" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="*" />
    <PackageReference Include="Newtonsoft.Json" Version="*" />
    <PackageReference Include="NuGet.Configuration" Version="*" />
    <PackageReference Include="NuGet.Packaging" Version="*" />
    <PackageReference Include="NuGet.Protocol" Version="*" />
    <PackageReference Include="NuGet.Versioning" Version="*" />
    <PackageReference Include="Serilog" Version="*" />
    <PackageReference Include="System.Collections.Immutable" Version="*" />
    <PackageReference Include="Arbor.ModelBinding.Primitives" Version="*-*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
    <_Parameter1>Milou.Deployer.Tests.Integration</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <PropertyGroup>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)\GeneratedFiles</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

</Project>