<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <PackAsTool>true</PackAsTool>
    <PackageId>Milou.Deployer.Bootstrapper.GlobalTool</PackageId>
    <OutputType>Exe</OutputType>
    <AssemblyName>milou-deploy</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2022.1.0" />
    <PackageReference Include="System.Collections.Immutable" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="*" />
    <PackageReference Include="Newtonsoft.Json" Version="*" />
    <PackageReference Include="NuGet.Versioning" Version="6.1.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Milou.Deployer.Bootstrapper.Common\Milou.Deployer.Bootstrapper.Common.csproj" />
  </ItemGroup>

</Project>
