<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2022.1.0" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="*" />
    <PackageReference Include="Microsoft.Web.Administration" Version="*" />
    <PackageReference Include="Microsoft.Win32.Registry" Version="*" />
    <PackageReference Include="Serilog" Version="*" />
    <PackageReference Include="System.Collections.Immutable" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Milou.Deployer.Core\Milou.Deployer.Core.csproj" />
  </ItemGroup>

</Project>
