<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Arbor.Tooler" Version="*-*" />
    <PackageReference Include="JetBrains.Annotations" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="*" />
    <PackageReference Include="Newtonsoft.Json" Version="*" />
    <PackageReference Include="NuGet.Versioning" Version="*" />
    <PackageReference Include="System.Collections.Immutable" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Milou.Deployer.Bootstrapper.Common\Milou.Deployer.Bootstrapper.Common.csproj" />
  </ItemGroup>

</Project>
