<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Arbor.App.Extensions" Version="*-*" />
    <PackageReference Include="JetBrains.Annotations" Version="*" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="*" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="*" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="*" />
    <PackageReference Include="System.Net.Http.Json" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="*" />
    <PackageReference Include="System.Collections.Immutable" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Milou.Deployer.Core\Milou.Deployer.Core.csproj" />
  </ItemGroup>

</Project>
