<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2022.3.1" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="7.0.0" />
    <PackageReference Include="Marten" Version="4.*" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.*" />
    <PackageReference Include="Arbor.KVConfiguration.Schema" Version="2.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="*" />
    <PackageReference Include="NuGet.Packaging" Version="6.*" />
    <PackageReference Include="NuGet.Versioning" Version="6.*" />
    <PackageReference Include="MediatR" Version="10.0.1" />
    <PackageReference Include="System.Collections.Immutable" Version="7.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Milou.Deployer.Web.Marten.Abstractions\Milou.Deployer.Web.Marten.Abstractions.csproj" />
    <ProjectReference Include="..\Milou.Deployer.Web.Core\Milou.Deployer.Web.Core.csproj" />
  </ItemGroup>

</Project>
