<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Arbor.AppModel" Version="0.12.0-build.1641561930" />
    <PackageReference Include="Arbor.Hypermedia" Version="0.4.0-build.1643038694" />
    <PackageReference Include="Arbor.ModelBinding.Generators" Version="2.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Arbor.ModelBinding.Primitives" Version="2.2.0" />
    <PackageReference Include="Arbor.Processing" Version="*" />
    <PackageReference Include="Arbor.KVConfiguration.Urns" Version="2.2.0" />
    <PackageReference Include="Arbor.Tooler" Version="0.16.0" />
    <PackageReference Include="JetBrains.Annotations" Version="2021.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="6.0.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="6.0.0" />
    <PackageReference Include="NuGet.Versioning" Version="6.0.0" />
    <PackageReference Include="System.Collections.Immutable" Version="6.0.0" />
    <PackageReference Include="Serilog" Version="*" />
    <PackageReference Include="Serilog.AspNetCore" Version="*" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="5.1.1" />
    <PackageReference Include="Polly.Extensions.Http" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="6.0.1" />
  </ItemGroup>

  <PropertyGroup>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)\GeneratedFiles</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

</Project>
