<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Arbor.App.Extensions" Version="*-*" />
    <PackageReference Include="Arbor.Hypermedia" Version="*-*" />
    <PackageReference Include="Arbor.ModelBinding.Generators" Version="*-*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Arbor.ModelBinding.Primitives" Version="*-*" />
    <PackageReference Include="Arbor.Processing" Version="*" />
    <PackageReference Include="Arbor.KVConfiguration.Urns" Version="*-*" />
    <PackageReference Include="Arbor.Tooler" Version="*-*" />
    <PackageReference Include="JetBrains.Annotations" Version="*" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="*" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="*" />
    <PackageReference Include="NuGet.Versioning" Version="*" />
    <PackageReference Include="System.Collections.Immutable" Version="*" />
    <PackageReference Include="Serilog" Version="*" />
    <PackageReference Include="Serilog.AspNetCore" Version="*" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="*" />
    <PackageReference Include="Polly.Extensions.Http" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="*" />
  </ItemGroup>

  <PropertyGroup>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)\GeneratedFiles</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

</Project>
