<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Arbor.AppModel" Version="0.12.0-build.1641561930" />
    <PackageReference Include="Arbor.KVConfiguration.Urns" Version="2.2.0" />
    <PackageReference Include="JetBrains.Annotations" Version="*" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.1.0" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="*" />
    <PackageReference Include="System.Collections.Immutable" Version="*" />
    <PackageReference Include="Newtonsoft.Json" Version="*" />
  </ItemGroup>

</Project>
