<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Arbor.Aesculus" Version="*" />
    <PackageReference Include="Arbor.Docker" Version="*" />
    <PackageReference Include="Arbor.Docker.Xunit" Version="*" />
    <PackageReference Include="FluentAssertions" Version="*" />
    <PackageReference Include="Newtonsoft.Json" Version="*" />
    <PackageReference Include="JetBrains.Annotations" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="*" />
    <PackageReference Include="NCrunch.Framework" Version="*" />
    <PackageReference Include="NuGet.Versioning" Version="*" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="*" />
    <PackageReference Include="Serilog.Sinks.XUnit" Version="*" />
    <PackageReference Include="System.Collections.Immutable" Version="*" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="*" />
    <PackageReference Include="xunit" Version="*" />
    <PackageReference Include="xunit.abstractions" Version="*" />
    <PackageReference Include="xunit.analyzers" Version="*" />
    <PackageReference Include="xunit.runner.console" Version="*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.runner.visualstudio" Version="*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Milou.Deployer.ConsoleClient\Milou.Deployer.ConsoleClient.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="TestData\AppDataTest\Target\App_Data\" />
  </ItemGroup>

</Project>