<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Arbor.AppModel" Version="0.12.0-build.1641561930" />
    <PackageReference Include="Arbor.KVConfiguration.Schema" Version="2.2.0" />
    <PackageReference Include="Arbor.ModelBinding.Generators" Version="*-*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Arbor.ModelBinding.Primitives" Version="*-*" />
    <PackageReference Include="DotNext.Threading" Version="*" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Arbor.ModelBinding" Version="*-*" />
    <PackageReference Include="Arbor.Processing" Version="*" />
    <PackageReference Include="Arbor.Tooler" Version="*-*" />
    <PackageReference Include="JetBrains.Annotations" Version="*" />
    <PackageReference Include="MailKit" Version="*" />
    <PackageReference Include="Marten" Version="*" />
    <PackageReference Include="MediatR" Version="9.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="*" />
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="*" />
    <PackageReference Include="Newtonsoft.Json" Version="*" />
    <PackageReference Include="NuGet.Frameworks" Version="*" />
    <PackageReference Include="NuGet.Packaging" Version="*" />
    <PackageReference Include="NuGet.Packaging.Core" Version="*" />
    <PackageReference Include="NuGet.Versioning" Version="*" />
    <PackageReference Include="Serilog" Version="*" />
    <PackageReference Include="Serilog.Sinks.Console" Version="*" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="*" />
    <PackageReference Include="Serilog.Sinks.File" Version="*" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="*" />
    <PackageReference Include="Serilog.Sinks.TextWriter" Version="*" />
    <PackageReference Include="System.Collections.Immutable" Version="*" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeStyle" Version="*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Milou.Deployer.Bootstrapper.Common\Milou.Deployer.Bootstrapper.Common.csproj" />
    <ProjectReference Include="..\Milou.Deployer.Core\Milou.Deployer.Core.csproj" />
    <ProjectReference Include="..\Milou.Deployer.Web.Agent\Milou.Deployer.Web.Agent.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Startup\" />
  </ItemGroup>
</Project>